### ISSUE TITLE
Empty password in BindAsync does not throw exception

### ISSUE THREAD

**Issue by Ainyru** [dsbenghe/Novell.Directory.Ldap.NETStandard#227] opened 2023-04-03 11:04 UTC
Using 4.0.0 version, method BindAsync throws exception when password is wrong except when password passed as "".

**Comment by klasen** [comment] 2023-06-09 07:30
This is working correctly. With an empty password, you are asking the server to perform an Unauthenticated Simple Bind: https://www.rfc-editor.org/rfc/rfc4513#section-5.1.2. 
Duplicate of #229

**Closed** 2023-07-05 20:27 UTC
