### ISSUE TITLE
SearchAsync runs forever if user not found

### ISSUE THREAD

**Issue by RyanGaudion** [dsbenghe/Novell.Directory.Ldap.NETStandard#215] opened 2022-09-05 12:28 UTC
We use this code to search for users:

`ILdapSearchResults results = await connection.SearchAsync(searchBase, LdapConnection.ScopeSub, searchFilter, attrs, false);`

and loop through the results with:

```
await foreach (LdapEntry entry in ldapSearchResults)
{
    if (entry == null) { continue; }
    return entry.GetAttributeSet();
}

```

When running this with a user that exists, the code returns the attribute set without issues however if the user doesn't exist the code hangs on this line `await foreach (LdapEntry entry in ldapSearchResults)` forever (over 20 mins).

**Comment by RyanGaudion** [comment] 2022-09-06 07:40
The issue occurs when Active Directory provides a LdapReferral to a server that the client doesn't have access to. Seems to be stuck in infinite loop

**Comment by dsbenghe** [comment] 2024-01-29 07:27
very likely duplicate of https://github.com/dsbenghe/Novell.Directory.Ldap.NETStandard/issues/195

**Comment by dsbenghe** [comment] 2024-04-01 14:55
close as duplicate of #195

**Closed by dsbenghe** 2024-04-01 14:55 UTC
