### ISSUE TITLE
Unable to connect AD (TLS) server on Linux machine

### ISSUE THREAD

**Issue by Sheetal1790** [dsbenghe/Novell.Directory.Ldap.NETStandard#231] opened 2023-06-16 08:41 UTC
### Discussed in https://github.com/dsbenghe/Novell.Directory.Ldap.NETStandard/discussions/230

<div type='discussions-op-text'>

<sup>Originally posted by **Sheetal1790** June 15, 2023</sup>
I have a web application that uses Novell.Directory.Ldap.NETStandard library to do Ldap search against Active Directory. 
On Windows machine I am able to connect and fetch details from both AD (TLS) and AD (Non-TLS) server. But when the application is deployed on Linux machine I am only able to connect to AD (Non-TLS)  server, while on AD (TLS) server I am getting below error:

**Below issue is displayed on Linux machine:**
_Unable to read data from the transport connection: Connection reset by peer._

**Below issue displayed on AD server:**
_An TLS 1.2 connection request was received from a remote client application, 
but none of the cipher suites supported by the client application are supported by the server. 
The SSL connection request has failed._

Is there any way to resolve this issue. Can anyone help on this?</div>

**Comment by dsbenghe** [comment] 2023-07-05 20:26
Duplicate of #230

**Closed by dsbenghe** 2023-07-05 20:26 UTC
